# Development Environment
name: viper-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click=8.1
  - rich=12.5
  - pydantic=1.8
  - toml=0.10
  - pip=22.2
  - pyside2=5.15
  #- pip:
  #  - PySide6
  # Testing and CI
  - pytest=7.1
  - pylint=2.15
  - pytest-pylint=0.18
  - pre-commit=2.20
  # Build and packaging
  - flit=3.7
  - conda=22.9
  - mamba=0.26
  - conda-build=3.22
  # Documentation
  - mkdocs=1.3
  - mkdocs-click=0.6
