# Development Environment
name: viper-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - conda=4.10.*
  # Build
  - sphinx=4.2.*
  - sphinx_rtd_theme=0.5.*
  - xonsh=0.10.*
  - pytest
  - python=3.7
  - setuptools=51.0.*
  - python=3.7
  - click=7.1.*
