# Viper environment configuration.  Run ids config --help for more info.
default_project_root = "/prj"

[docs]
viper = "http://www.cascode-labs.org/viper/"
viper-forge = "https://www.cascode-labs.org/viper-forge/"
