{% set name = "viper" %}
{% set version = "0.1.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - path: ../bin
    folder: bin
  - path: ../viper
    folder: viper
  - path: ../viper.init.il
  - path: ../viper.lmgrinit
  - path: ../README.md
  - path: ../conda-recipe
    folder: conda-recipe
  - path: ../conda-recipe
  - path: ../setup.py
  - path: ../docs-src
    folder: docs-src
requirements:
  build:
    - python=3.7
    - setuptools=51.0.*
  run:
    - python=3.7
    - click=7.1.*

build:
  number: 1
  entry_points:
    - sp=viper.sp:sp
    - viper=viper.cli:viper

test:
  imports:
    - viper
  commands:
    - sp --help
    - viper --help

about:
  home: https://cascode-labs.github.io/viper
  license: MIT
  summary: Easily initialize IC automation projects in Cadence Virtuoso using Conda
  description: |
    viper enables IC automation projects to be easily initialized.
    The sp command starts virtuoso in the specified conda environment.
  dev_url: https://github.com/cascode-labs/viper
  doc_url: https://cascode-labs.github.io/viper
  doc_source_url: https://github.com/cascode-labs/viper/docs
