name: viper-build
channels:
  - defaults
  - conda-forge
dependencies:
  - conda=4.9.2
  - conda-build=3.20.5
  - conda-verify=3.4.2
  - sphinx=1.8.*
  - recommonmark=0.6.*
  - sphinx_rtd_theme=0.4.*
  - xonsh
