name: Build
# Releases to the dev channel

on: [workflow_dispatch]

env:
  DEV_CHANNEL: "/prj/ids/ids-conda/channels/dev-skyworks"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Conda Package
        uses: cascode-labs/build-conda-action@v0.1.0